<h1 style='font-size:40px'> SVD</h1>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Essas anotações surgiram como uma consequência dos primeiros tópicos do capítulo 4. O objetivo aqui é entender a maneira como o objeto LinearRegression obtém os seus coeficietes com o uso de matrizes pseudo-inversas.
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> 
    <a href='https://www.youtube.com/watch?v=TQvxWaQnrqI&t=445s'>Eigenvectors and Eigenvalues</a>
</h2>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Há situações em que, dada uma matriz quadrada A, se a multiplicarmos por um vetor $\vec{x}$, teremos como resultado esse mesmo vetor multiplicado por um número $\lambda$.
                $$
                    A\vec{x}=\lambda\vec{x}
                $$
        </li>
        <li> 
            Nesse cenário, $\vec{x}$ é reconhecido como autovetor (Eigenvector) e $\lambda$ como autovalor (Eigenvalue).
        </li>
        <li> 
            <u> Observação</u>: O Eigenvector não pode ser o vetor zero ($\vec{0}$)
        </li>
    </ul>
</div>

<h3 style='font-size:30px;font-style:italic'> Encontrando os Eigenvalues</h3>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Se subtrairmos $\lambda \vec{x}$ em ambos os lados da equação e multiplicarmos esse mesmo termo de subtração no lado esquerdo da equação pela matriz identidade, teremos como resultado $A\vec{x}-\lambda I \vec{x}=\vec{0}$. Colocando $\vec{x}$ em evidência:
            $$
                \vec{x}(A-\lambda I)=\vec{0}
            $$
        </li>
        <li> 
            Para que essa equação seja plenamente satisfeita sem que $\vec{x}=\vec{0}$, a matriz $(A-\lambda I) $ não pode ser invertível e, portanto, deve ter seu determinante igual a zero!
            $$
            |A-\lambda I|=0
            $$
        </li>
        <li> 
            Resolvendo a equação acima, obtemos os Eigenvalues da matriz A.
        </li>
    </ul>
</div>

<h3 style='font-size:30px;font-style:italic'> Encontrando os Eigenvectors</h3>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Tendo os Eigenvalues em mãos, podemos implantá-los em $A-\lambda I$ e encontrar $\vec{x}$.
        </li>
        <li> 
            O resultado final não será um vetor em si, mas uma infinidade de vetores $\vec{x}$ cujos valores respeitem as proporções dadas pelos resultados do dot product. Observe a resolução de um problema tendo $\lambda=3$.
        </li>
        <img src='eigenvector.png'>
        <li> 
            No caso da imagem, consideramos $x_1=1$ e, portanto, $x_2=2$, mas qualquer vetor $\begin{bmatrix}x_1\\2x_1\end{bmatrix}$ pode ser considerado um Eigenvector.
        </li>
    </ul>
</div>

In [20]:
A = np.array([[1,1],[4,1]])
np.linalg.eigvals(A)

array([ 3., -1.])

In [30]:
np.linalg.svd(A)

(array([[-0.28978415, -0.95709203],
        [-0.95709203,  0.28978415]]),
 array([4.30277564, 0.69722436]),
 array([[-0.95709203, -0.28978415],
        [ 0.28978415, -0.95709203]]))

In [29]:
from scipy.linalg import svd
np.linalg.svd(A)
svd(A)

(array([[-0.28978415, -0.95709203],
        [-0.95709203,  0.28978415]]),
 array([4.30277564, 0.69722436]),
 array([[-0.95709203, -0.28978415],
        [ 0.28978415, -0.95709203]]))

<p style='color:red'>Ver esse<a href='https://www.youtube.com/watch?v=TQvxWaQnrqI&t=445s'> vídeo</a> (6:30)</p>