<h1 style='font-size:40px'> Training Models</h1>

<h2 style='font-size:30px'> Esclarecimentos</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Este é o meu segundo estudo sobre o quarto capítulo do livro. O objetivo deste registro é, agora, consolidar o meu entendimento sobre a esfera matemática do treinamento em Machine Learning.
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> Notations (p.43)</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
            m é o tamanho do dataset com o qual avaliamos o modelo.
            <ul style='list-style-type:circle'> 
                <li> 
                    Se o set de validação tem 5000 instâncias, $m=5000$
                </li>
            </ul>
        </li>
        <li style='margin-top:10px'> 
            $x^{(i)}$ é o vetor com os valores de todas as features independentes da i-ésima instância do dataset. $y^{(i)}$ é a sua variável-alvo.
            <ul style='list-style-type:circle'> 
                <li> 
                    Se a nona feature do dataset tem como features independentes 200, 4500, 100 e 9 $x^{(9)}=\begin{bmatrix} 200\\4500\\1000\\9\end{bmatrix}$. 
                </li>
                <li> 
                    Caso sua target-variable seja 3, $y^{(9)}=\begin{bmatrix}3\end{bmatrix}$
                </li>
            </ul>
        </li>
        <li style='margin-top:10px'> 
            X é a matrix com os valores das features independentes de cada instância. Esses, por sua vez, estão contidos em um vetor-linha, e não coluna. Portanto, para um dataset com 2000 instâncias:
            $$
                X=\begin{bmatrix} 
                (x^{(1)})^{T} \\
                (x^{(2)})^{T} \\
                \vdots \\
                (x^{(2000)})^{T}
                \end{bmatrix}
            $$
        </li>
        <li style='margin-top:10px'> 
            $h$ representa o nosso modelo de ML, que, para cada instância, lança uma previsão $ŷ$. Dessa maneira, $h(x^{(i)})=ŷ^{(i)}$
             <ul style='list-style-type:circle'> 
                <li> 
                    O erro absoluto de um algoritmo regressor será $ŷ^{(i)}-y^{(i)}$
                </li>
            </ul>
        </li>
        <li style='margin-top:10px'> 
            $RMSE(X, h)$, $R^{2}(X,h)$ representam a função custo aplicada no set $X$ com o modelo $h$. 
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> Métricas de Regressão</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
             RMSE, também conhecida como Euclidean Norm ou $l_2$ norm. Sua fórmula é:
            $$
            RMSE(X,h)=\sqrt{\frac{1}{m}\sum_{i=1}^{m}(h(x^{(i)})-y^{(i)})^{2}}
            $$
        </li>
        <li style='margin-top:10px'> 
            MAE, também conhecida como Manhattan Norm ou $l_1$ norm. Sua fórmula é:
            $$
                    MAE(X,h)=\frac{1}{m}\sum_{i=1}^{m} |h(x^{(i)})-y^{(i)}| 
            $$
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> Início de Fato do Capítulo</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
            Neste capítulo, aprenderemos os principais métodos de treinamento em ML, assim como alguns modelos mais simples.
        </li>
        <li> 
            Há maneiras mais diretas de alcançarmos os parâmetros ideais do modelo, e outras que envolvem iterações.
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> Linear Regression</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
            A Regressão Linear é o modelo mais simples do ML. Consiste na soma ponderada de cada feature por um coeficiente. Uma previsão ŷ é dada como:
            <p>$
                ŷ=\theta_0 + \theta_1 x_1 + \theta_2 x_2 + \dots + \theta_n x_n
            $ ($\theta_0$ é o termo de bias).
            </p>         
        </li>
        <li> 
            Uma maneira mais concisa de formular essa equação é:
            $$
                ŷ=h_{\theta}(x)=\theta \cdot x
            $$
            <ul style='list-style-type:circle'> 
                <li> 
                    $\theta$ é o vetor com os coeficientes do modelo.
                </li>
                <li> 
                    x é o vetor com os valores das features.
                </li>
                <li> 
                    $\theta \cdot x$ é o produto escalar entre os vetores mencionados, igual a $\theta_0 + \theta_1 x_1 + \theta_2 x_2 + \dots + \theta_n x_n
            $
                </li>
            </ul>
        </li>
        <li> 
            Nota: A previsão do modelo ainda pode ser dada como $ŷ=\theta^{T}x$, que é a multiplicação entre a transposta dos coeficientes e x.
        </li>
    </ul>
</div>

In [1]:
import numpy as np
theta = np.random.random(size=3)
x = np.random.normal(size=3)

# Observe como o dot product e a multiplicação matricial se equivalem.
theta.dot(x), theta.T@x

(-1.2753030570997286, -1.2753030570997286)

<div> 
    <ul style='font-size:20px'>
        <li> 
             A criação de uma Regressão Linear envolve encontrar o $\theta$ que minimiza o MSE. Agora, é hora de explorarmos os diferentes métodos para que isso ocorra.        
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> The Normal Equation</h2>

<div> 
    <ul style='font-size:20px'>
        <li> 
             A Equação Normal é uma maneira direta de alcançarmos o $\theta$ minimizador do MSE. A sua fórmula é:
            $$
                \theta=(X^{T}X)^{-1}X^{T}y
            $$
            <ul style='list-style-type:circle'> 
                <li> 
                    y é o vetor com as target variables.
                </li>
            </ul>
        </li>
    </ul>
</div>

In [2]:
# Aplicando a Equação Normal com o Numpy.
X = np.random.normal(size=(1000,1))
y = 10 + 4*X - np.random.normal(size=(1000,1))

# Adicionando a coluna de bias a X.
X_b = np.c_[np.ones((1000,1)), X]
theta_best = np.linalg.inv(X_b.T@X_b) @ X_b.T @ y
theta_best

array([[10.02114206],
       [ 3.97259494]])

In [3]:
# Fazendo uma previsão com uma nova instância.
X_new = np.array([5])
X_new_b = np.c_[np.ones((1,1)), X_new]

X_new_b.dot(theta_best)

array([[29.88411678]])

In [4]:
# Essa mesma equação poderia ser escrita com os dot products entre as matrizes.
np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

array([[10.02114206],
       [ 3.97259494]])

In [5]:
# O 'LinearRegression' obtém os mesmos parâmetros.
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X,y)
lin_reg.intercept_, lin_reg.coef_

(array([10.02114206]), array([[3.97259494]]))

<h3 style='font-size:30px;font-style:italic'> Moore-Penrose Inverse</h3>
<div> 
    <ul style='font-size:20px'>
        <li> 
             Uma outra maneira de obtermos os coeficientes da nossa Regressão Linear é com o produto escalar entre a matriz Moore-Penrose de X (conhecida também como pseudoinversa) e y.
            $$
                \theta=X^{+}y
            $$
        </li>
    </ul>
</div>

In [6]:
# Use 'np.linalg.pinv' para computar a pseudoinversa de X.
theta_best = np.linalg.pinv(X_b).dot(y)
theta_best

array([[10.02114206],
       [ 3.97259494]])

<h2 style='font-size:30px'> Computational Complexity</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
            A Time Complexity para treinamento de uma Regressão Linear com a Normal Equation pode ser de $O(n^{2.4})$ a $O(n^{3})$ e $O(n^{2})$ com a Inversa Moore-Penrose (sendo n o número de features). Ambos os métodos são $O(m)$ (m é o número de instâncias).
        </li>
        <li> 
            Com previsões, ambas as estratégias têm $O(n)$ e $O(m)$. 
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> Gradient Descent</h2>
<div> 
    <ul style='font-size:20px'>
        <li> 
            O autor introduz os conceitos de Descida de Gradiente e learning rates.
        </li>
    </ul>
</div>

<h3 style='font-size:30px;font-style:italic'> Batch Gradient Descent</h3>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            O Batch Gradient Descent consiste em fazer a descida de gradiente com base em todo o conjunto de treino. O Gradiente de uma MSE para a Regressão Linear é dado como:
            <p style='margin-top:10px'>
            $$
                \nabla_{\theta}MSE(\theta)=
                    \begin{bmatrix} 
                        \frac{\delta}{\delta\theta_{0}}MSE(\theta) \\ 
                        \frac{\delta}{\delta\theta_{1}}MSE(\theta) \\
                        \vdots \\
                        \frac{\delta}{\delta\theta_{n}}MSE(\theta) 
                    \end{bmatrix}                    
                    = \frac{2}{m}X^{T}(X\theta-y)
            $$
            </p>
        </li>
    </ul>
</div>

In [18]:
# Aplicando a Batch Gradient Descent em código.

eta = .01 # learning rate.
n_iterations = 1000 # número de iterações total.

# Inicialização aleatória dos parâmetros (segundo uma Distribuição Normal).
theta = np.random.uniform(size=(2,1))

for i in range(n_iterations):
    gradient = 2/len(X_b) * X_b.T.dot(X_b.dot(theta) - y)
    theta -=  eta*gradient

<p style='color:red'> Stochastic Gradient Descent